# Generated by Django 4.0.1 on 2022-06-17 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='shifts',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='shifts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.shift'),
        ),
    ]
