# Generated by Django 4.0.1 on 2022-06-17 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0010_alter_shift_base_pay_alter_shift_evening_penalties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
