# Generated by Django 4.0.1 on 2022-06-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_shift_total_pay_alter_shift_base_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
