# Generated by Django 4.0.1 on 2022-06-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_shift_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='meal_break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='meal_break_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='meal_break_taken',
            field=models.BooleanField(default=False),
        ),
    ]
