# Generated by Django 4.0.1 on 2022-06-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_shift_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
