# Generated by Django 4.0.1 on 2022-06-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_shift_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='total_earned',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
