# Generated by Django 4.0.1 on 2022-06-17 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_shift_sunday_pay_shift_base_pay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='Sunday_Pay',
            new_name='sunday_pay',
        ),
    ]
