# Generated by Django 4.0.1 on 2022-06-17 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_shift_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='total_pay',
        ),
        migrations.AlterField(
            model_name='shift',
            name='base_pay',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='evening_penalties',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='holiday_pay',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='night_penalties',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='overtime_level_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='overtime_level_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='overtime_weekend',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='saturday_pay',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='sunday_pay',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.usermodel'),
        ),
    ]
